```{r}
speaqeasy_data <- file.path(tempdir(), "rse_speaqeasy.RData")
download.file("https://github.com/LieberInstitute/SPEAQeasy-example/blob/master/rse_speaqeasy.RData?raw=true", speaqeasy_data, mode = "wb")
library("SummarizedExperiment")
load(speaqeasy_data, verbose = TRUE)

rse_gene

cosito <- data.frame(rse_gene$totalAssignedGene, rse_gene$mitoRate, rse_gene$PrimaryDx)
cosito
control <- cosito[ rse_gene$PrimaryDx == 'Control',]
bipolar <- cosito[ rse_gene$PrimaryDx == 'Bipolar',]

match('SNAP25',rowRanges(rse_gene)$Symbol)

genePos <- match('SNAP25',rowRanges(rse_gene)$Symbol)
cuentas <- as.vector(assay(rse_gene[genePos,], "counts")) 
cositoCuen <- cbind(cosito, cuentas)
bipolarCuen <- cositoCuen[cositoCuen$rse_gene.PrimaryDx == "Bipolar",]
controlCuen <- cositoCuen[cositoCuen$rse_gene.PrimaryDx == "Control", ] 
boxplot(x = cbind(controlCuen$cuentas,bipolarCuen$cuentas), names= c('Control', 'Bipolar'))
```

```{r}
dfCdmx <- as.data.frame(cbind(as.vector(rse_gene$BrainRegion),as.vector(rse_gene$PrimaryDx))) 
names(dfCdmx) <- c('BrainRegion','PrimaryDx') 
vd <- ExploreModelMatrix::VisualizeDesign( sampleData = dfCdmx, designFormula = ~ BrainRegion + PrimaryDx, textSizeFitted = 4 ) 
cowplot::plot_grid(plotlist = vd$plotlist)

app <- ExploreModelMatrix(
    sampleData = sampleData,
    designFormula = ~ genotype + treatment
)
if (interactive()) shiny::runApp(app)
```

